
val a = new simpleBunch()
val y = List(1, 1, 2, 3, 5, 8)
val z = List(1,2,3,2,1)
a.last(y)
a.lastRecursive(y)
a.penultimate(y)
a.nth(2, y)
a.length(y)
a.reverse(y)
a.reverse2(y)
a.isPalindrome(y)
a.isPalindrome(z)
y.isInstanceOf[List[Int]]
val b= List(1,2,3)++List(4,5)
a.flatten(List(List(1, 1), 2, List(3, List(5, 8))))
val t = List('a, 'a, 'a, 'a, 'b, 'c, 'c, 'a, 'a, 'd, 'e, 'e, 'e, 'e)
a.compress(t)
a.pack(t)
a.encode(t)